### PR TITLE
Update _header.scss

### PR DESCRIPTION
**Pull request by Willmish**
TYPO in dark-color variable

### CODE REVIEW

**Comment by Asday** [comment]
...  Huh.

First I checked the code 'cause I'm a Python main, so underscores are more natural to me and I figured that was fine, but it's a hyphen in the definition.  Then I checked the live site 'cause I was sure everything looked how I wanted, and the compiled CSS has the correct hexcode.  Finally I hit google up and found [this](https://github.com/sass/sass/issues/334#issuecomment-4687066).

What bizarre behaviour.

How strange of you to find it.  I'm actually quite interested how, if you would be so kind.

**Comment by Willmish** [comment]
Hi,
Didn't know hyphens and underscores are treated as the same thing in SASS. Good to know :)

I am currently in the process of making my own personal website based on the m10c theme, but I can't get the sites colours to change even though the hugo variables do change so I was looking at other forks to see if they had a similar issue and how they fixed it. 

So far no luck, but because I was intentionally looking for hugo and css variables in ur code, I stumbled upon the typo.

So that's the story hah. Though Im curious whether you made any changes to the original theme to get the params.style working.

**Comment by Asday** [comment]
It was quite a long time ago now, but I don't recall doing anything particularly special.  All I remember to do with the CSS was not liking the huge line uh...  [Here](https://github.com/Asday/righttobeoffensive.com/blob/4534101061686197e1996bf03193a2ff6ed514d3/themes/rtbo/layouts/_default/baseof.html#L22), which I couldn't figure out how to split.  It might just be the only >80 character line in the project.  :(

I'm on zero sleep and less motivation right now, but if you wanna drop a link to your repo and some pointers to the files in question, I could have a look some time later, maybe tomorrow.

**Comment by Willmish** [comment]
That would be awesome.

**Comment by Willmish** [comment]
That would be awesome.
Here is my [repo](https://github.com/Willmish/personal-website-hugo).

Basically, I change different variables in params.style (darkestColor, darkColor etc.) in the [config.toml ](https://github.com/Willmish/personal-website-hugo/blob/2780f6b38fc5d28f8a253a140213cec1e3c08e7a/config.toml#L23)file.

The problem is none of those colours are actually changed, I've even changed the variables in the [main.css](https://github.com/Willmish/personal-website-hugo/blob/2659da76853b933e643e420f5005c654f86a0eca/themes/m10c/assets/css/main.scss#L1) file to smth like black or white to see anything, but the colors stayed the same.

I've narrowed it down to these [files](https://github.com/Willmish/personal-website-hugo/tree/master/themes/m10c/resources/_gen/assets/scss/css), without which the website won't build, but if I change the colour in the horrible one-liner inside [.content ](https://github.com/Willmish/personal-website-hugo/blob/master/themes/m10c/resources/_gen/assets/scss/css/main.scss_e86386c8bae1cd02295de71a1be078d6.content)file it does appear on the main website.

So it simply seems like the values changed by hugo are overridden by those resources files.

I am a newbie to hugo, so I'm not fully sure what I am doing hah.

**Pull request merged**
